#!/usr/bin/env python3
"""
Fetch recent tweets from X/Twitter and write _data/featured_tweets.yml.

Uses ntscraper (via Nitter instances) - free but can be unreliable when Nitter
instances are down. If the fetch fails, the existing YAML file is left unchanged.

Alternative: Set TWITTER_BEARER_TOKEN for the official API (requires paid X
developer account). When set, this script uses the API instead of ntscraper.

Run before Jekyll build to keep the sidebar tweets up to date.
"""
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional

OUTPUT_FILE = Path(__file__).resolve().parent.parent / "_data" / "featured_tweets.yml"
USERNAME = os.environ.get("TWITTER_USERNAME", "Al_Murphy_")
MAX_TWEETS = 5


def fetch_via_api() -> Optional[List[Dict]]:
    """Fetch tweets using Twitter API v2 if Bearer token is set."""
    token = os.environ.get("TWITTER_BEARER_TOKEN")
    if not token:
        return None

    try:
        import requests

        # Resolve username to user ID
        resp = requests.get(
            f"https://api.twitter.com/2/users/by/username/{USERNAME}",
            headers={"Authorization": f"Bearer {token}"},
            timeout=15,
        )
        resp.raise_for_status()
        user_id = resp.json()["data"]["id"]

        # Fetch recent tweets
        resp = requests.get(
            f"https://api.twitter.com/2/users/{user_id}/tweets",
            headers={"Authorization": f"Bearer {token}"},
            params={"max_results": MAX_TWEETS, "exclude": "replies,retweets"},
            timeout=15,
        )
        resp.raise_for_status()
        data = resp.json()
        tweets = data.get("data", [])

        return [{"url": f"https://x.com/{USERNAME}/status/{t['id']}"} for t in tweets]
    except Exception as e:
        print(f"Twitter API error: {e}", file=sys.stderr)
        return None


def fetch_via_ntscraper() -> Optional[List[Dict]]:
    """Fetch tweets using ntscraper (Nitter). May fail when instances are down."""
    try:
        from ntscraper import Nitter

        scraper = Nitter(log_level=0, skip_instance_check=True)
        result = scraper.get_tweets(USERNAME, mode="user", number=MAX_TWEETS)

        if not result or "tweets" not in result:
            return None

        urls = []
        for t in result["tweets"]:
            url = None
            if isinstance(t, dict):
                url = t.get("tweet_url") or t.get("link") or t.get("url")
                if not url and t.get("tweet_id"):
                    url = f"https://x.com/{USERNAME}/status/{t['tweet_id']}"
            else:
                url = getattr(t, "tweet_url", None) or getattr(t, "link", None)
                if not url and hasattr(t, "tweet_id"):
                    url = f"https://x.com/{USERNAME}/status/{t.tweet_id}"

            if url and "status/" in str(url):
                urls.append({"url": str(url)})

        return urls if urls else None
    except Exception as e:
        print(f"ntscraper error: {e}", file=sys.stderr)
        return None


def write_yaml(tweets: List[Dict]) -> None:
    """Write tweets to YAML file."""
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/fetch_featured_tweets.py",
        "# Source: https://x.com/" + USERNAME,
        "",
    ]
    for t in tweets:
        url = t["url"].replace('"', '\\"')
        lines.append(f'- url: "{url}"')
    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    tweets = None

    # Prefer API if credentials are set
    if os.environ.get("TWITTER_BEARER_TOKEN"):
        tweets = fetch_via_api()

    # Fall back to ntscraper
    if not tweets:
        tweets = fetch_via_ntscraper()

    if tweets:
        write_yaml(tweets)
        print(f"Wrote {len(tweets)} tweets to {OUTPUT_FILE}")
        return 0

    if OUTPUT_FILE.exists():
        print("Fetch failed. Keeping existing featured_tweets.yml.", file=sys.stderr)
    else:
        print(
            "Fetch failed and no existing file. Add tweets manually to _data/featured_tweets.yml.",
            file=sys.stderr,
        )
    return 0  # Don't fail the build


if __name__ == "__main__":
    sys.exit(main())
