#!/usr/bin/env python3
"""
Fetch tweets from a Twitter RSS feed and write _data/twitter_rss.yml.

Twitter/X no longer offers native RSS. Use a third-party service to create a feed:
- RSS.app (rss.app) - Free plan: 5 feeds, 24hr updates. Paste your X profile URL.
- Create feed at https://rss.app/rss-feed/create-twitter-rss-feed

Set the feed URL via:
- TWITTER_RSS_URL env var, or
- twitter_rss_url in _config.yml

Run before Jekyll build to keep the sidebar tweets up to date.
"""
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

OUTPUT_FILE = Path(__file__).resolve().parent.parent / "_data" / "twitter_rss.yml"
CONFIG_FILE = Path(__file__).resolve().parent.parent / "_config.yml"
MAX_ITEMS = 8


def get_feed_url() -> Optional[str]:
    """Get RSS feed URL from env or config."""
    url = os.environ.get("TWITTER_RSS_URL")
    if url:
        return url.strip()
    try:
        text = CONFIG_FILE.read_text(encoding="utf-8")
        # Match twitter_rss_url: "url" or twitter_rss_url: url
        m = re.search(r'twitter_rss_url:\s*["\']?([^"\'\s#]+)["\']?', text)
        return m.group(1).strip() if m else None
    except Exception:
        return None


def strip_html(html: str) -> str:
    """Remove HTML tags and decode entities."""
    if not html:
        return ""
    text = re.sub(r"<[^>]+>", " ", html)
    text = text.replace("&nbsp;", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text[:200] + ("..." if len(text) > 200 else "")


def fetch_rss(feed_url: str) -> Optional[List[Dict[str, Any]]]:
    """Fetch and parse RSS/Atom feed."""
    try:
        import feedparser
    except ImportError:
        print("Install feedparser: pip install feedparser", file=sys.stderr)
        return None

    try:
        feed = feedparser.parse(feed_url, request_headers={"User-Agent": "Jekyll-RSS-Fetcher/1.0"})
    except Exception as e:
        print(f"Fetch error: {e}", file=sys.stderr)
        return None

    if feed.bozo and not feed.entries:
        print(f"Parse error: {feed.bozo_exception}", file=sys.stderr)
        return None

    items = []
    for entry in feed.entries[:MAX_ITEMS]:
        title = strip_html(entry.get("title", "")) or "(Tweet)"
        link = entry.get("link", "")
        if not link:
            continue
        # Parse date
        date_str = ""
        if hasattr(entry, "published_parsed") and entry.published_parsed:
            from time import struct_time
            t = entry.published_parsed
            date_str = f"{t.tm_year:04d}-{t.tm_mon:02d}-{t.tm_mday:02d}"
        elif hasattr(entry, "updated_parsed") and entry.updated_parsed:
            t = entry.updated_parsed
            date_str = f"{t.tm_year:04d}-{t.tm_mon:02d}-{t.tm_mday:02d}"
        content = strip_html(entry.get("summary", "") or entry.get("description", ""))
        items.append({
            "title": title,
            "url": link,
            "date": date_str,
            "excerpt": content[:150] + ("..." if len(content) > 150 else "") if content else "",
        })
    return items


def write_yaml(items: List[Dict[str, Any]]) -> None:
    """Write items to YAML file."""
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/fetch_twitter_rss.py",
        "# Source: Twitter RSS feed",
        "",
    ]
    for item in items:
        title = item["title"].replace('"', '\\"')
        url = item["url"].replace('"', '\\"')
        lines.append(f'- title: "{title}"')
        lines.append(f'  url: "{url}"')
        lines.append(f'  date: "{item["date"]}"')
        if item.get("excerpt"):
            exc = item["excerpt"].replace('"', '\\"')
            lines.append(f'  excerpt: "{exc}"')
        lines.append("")
    OUTPUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    feed_url = get_feed_url()
    if not feed_url:
        print(
            "No Twitter RSS URL. Set TWITTER_RSS_URL or twitter_rss_url in _config.yml. "
            "Create a feed at https://rss.app/rss-feed/create-twitter-rss-feed",
            file=sys.stderr,
        )
        return 0  # Don't fail build

    items = fetch_rss(feed_url)
    if items:
        write_yaml(items)
        print(f"Wrote {len(items)} tweets to {OUTPUT_FILE}")
        return 0

    if OUTPUT_FILE.exists():
        print("Fetch failed. Keeping existing twitter_rss.yml.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
