#!/usr/bin/env python3
"""
Fetch recent tweets via ntscraper (Nitter) and write _data/tweets.yml.

Uses ntscraper which scrapes from Nitter instances - free but Nitter instances
can be unreliable. If the fetch fails, the existing tweets.yml is kept.

Run in GitHub Actions before each build to keep the sidebar up to date.
"""
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

OUTPUT_FILE = Path(__file__).resolve().parent.parent / "_data" / "tweets.yml"
USERNAME = os.environ.get("TWITTER_USERNAME", "Al_Murphy_")
MAX_TWEETS = 5


def fetch_tweets() -> Optional[List[Dict[str, Any]]]:
    """Fetch tweets using ntscraper (Nitter)."""
    try:
        from ntscraper import Nitter
    except ImportError:
        print("ntscraper not installed. Run: pip install ntscraper", file=sys.stderr)
        return None

    try:
        scraper = Nitter(log_level=0, skip_instance_check=False)
        result = scraper.get_tweets(USERNAME, mode="user", number=MAX_TWEETS)
    except Exception as e:
        print(f"ntscraper error: {e}", file=sys.stderr)
        return None

    if not result or "tweets" not in result or not result["tweets"]:
        return None

    items = []
    for t in result["tweets"]:
        url = None
        text = ""
        date_str = ""

        if isinstance(t, dict):
            url = t.get("tweet_url") or t.get("link")
            if not url and t.get("tweet_id"):
                url = f"https://x.com/{USERNAME}/status/{t['tweet_id']}"
            text = (t.get("text") or t.get("content") or "").strip()
            if t.get("date"):
                date_str = _parse_date(t["date"])
        else:
            url = getattr(t, "tweet_url", None) or getattr(t, "link", None)
            if not url and hasattr(t, "tweet_id"):
                url = f"https://x.com/{USERNAME}/status/{t.tweet_id}"
            text = (getattr(t, "text", None) or getattr(t, "content", None) or "").strip()
            if hasattr(t, "date") and t.date:
                date_str = _parse_date(str(t.date))

        if not url or "status/" not in str(url):
            continue

        # Truncate long tweets for sidebar display
        title = (text[:120] + "…") if len(text) > 120 else (text or "Tweet")
        # Escape for YAML
        title = title.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
        items.append({"title": title, "url": str(url), "date": date_str or "2024-01-01"})

    return items if items else None


def _parse_date(s: str) -> str:
    """Try to extract YYYY-MM-DD from date string."""
    if not s:
        return ""
    # Match patterns like "Dec 11, 2024", "2024-12-11", "11 Dec 2024"
    m = re.search(r"(\d{4})-(\d{2})-(\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
    months = {"jan": "01", "feb": "02", "mar": "03", "apr": "04", "may": "05", "jun": "06",
              "jul": "07", "aug": "08", "sep": "09", "oct": "10", "nov": "11", "dec": "12"}
    m = re.search(r"(\d{1,2})\s+(\w{3})\w*\s+(\d{4})", s, re.I)
    if m:
        day, mon, year = m.groups()
        return f"{year}-{months.get(mon[:3].lower(), '01')}-{day.zfill(2)}"
    m = re.search(r"(\w{3})\w*\s+(\d{1,2}),?\s+(\d{4})", s, re.I)
    if m:
        mon, day, year = m.groups()
        return f"{year}-{months.get(mon[:3].lower(), '01')}-{day.zfill(2)}"
    return ""


def write_yaml(items: List[Dict[str, Any]]) -> None:
    """Write tweets to YAML file."""
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/fetch_tweets.py",
        "# Source: https://x.com/" + USERNAME,
        "",
    ]
    for item in items:
        lines.append(f'- title: "{item["title"]}"')
        lines.append(f'  url: "{item["url"]}"')
        lines.append(f'  date: "{item["date"]}"')
        lines.append("")
    OUTPUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    items = fetch_tweets()
    if items:
        write_yaml(items)
        print(f"Wrote {len(items)} tweets to {OUTPUT_FILE}")
        return 0
    if OUTPUT_FILE.exists():
        print("Fetch failed. Keeping existing tweets.yml.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
