#!/usr/bin/env python3
"""
Fetch blog posts by Alan Murphy from Genomics × AI and write _data/genomicsxai_blogs.yml.
Run before Jekyll build to keep the right sidebar up to date.
"""
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import requests
from bs4 import BeautifulSoup

AUTHOR_URL = "https://genomicsxai.github.io/authors/alan-murphy/"
OUTPUT_FILE = Path(__file__).resolve().parent.parent / "_data" / "genomicsxai_blogs.yml"
BASE_URL = "https://genomicsxai.github.io"


def fetch_page(url: str) -> str:
    """Fetch page HTML with a reasonable User-Agent."""
    resp = requests.get(url, timeout=15, headers={"User-Agent": "Jekyll-Blog-Fetcher/1.0"})
    resp.raise_for_status()
    return resp.text


def parse_date(text: str) -> Optional[str]:
    """Parse date string to YYYY-MM-DD. Handles formats like 'Wednesday, February 25, 2026'."""
    if not text or not text.strip():
        return None
    text = text.strip()
    # Try common formats
    for fmt in ("%A, %B %d, %Y", "%B %d, %Y", "%Y-%m-%d", "%d %B %Y"):
        try:
            dt = datetime.strptime(text[:50], fmt)
            return dt.strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def extract_posts(html: str):
    """Extract blog post entries from the author page HTML."""
    soup = BeautifulSoup(html, "html.parser")
    posts = []
    seen_urls = set()

    # Find all links to /blogs/ (post URLs)
    for a in soup.find_all("a", href=True):
        href = a.get("href", "")
        if "/blogs/" not in href:
            continue

        # Normalize URL
        if href.startswith("/"):
            url = BASE_URL + href
        elif href.startswith("http"):
            url = href
        else:
            url = BASE_URL + "/" + href

        if url in seen_urls:
            continue

        title = (a.get_text() or "").strip()
        if not title or len(title) < 5:
            continue

        # Skip nav/header links
        if "Genomics" in title and "AI" in title and len(title) < 25:
            continue

        # Try to find date - look in parent/siblings
        date_str = None
        parent = a.parent
        for _ in range(5):
            if not parent:
                break
            # Look for <time datetime="...">
            time_el = parent.find("time", datetime=True)
            if time_el:
                dt = time_el.get("datetime", "")
                if re.match(r"\d{4}-\d{2}-\d{2}", dt):
                    date_str = dt[:10]
                    break
            # Look for date-like text
            for s in parent.find_all(string=True):
                if re.search(r"\d{4}", str(s)) and re.search(r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)", str(s), re.I):
                    parsed = parse_date(str(s))
                    if parsed:
                        date_str = parsed
                        break
            if date_str:
                break
            parent = parent.parent

        # Fallback: extract from URL (e.g. /blogs/2026-003/ -> 2026)
        if not date_str:
            match = re.search(r"/blogs/(\d{4})-(\d+)/", url)
            if match:
                year, num = match.groups()
                date_str = f"{year}-01-01"  # Approximate

        posts.append({
            "title": title,
            "url": url.rstrip("/") + "/",
            "date": date_str or "2026-01-01",
            "excerpt": "",
        })
        seen_urls.add(url)

    # Sort by date descending
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def write_yaml(posts):
    """Write posts to YAML file."""
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/fetch_genomicsxai_blogs.py",
        "# Source: https://genomicsxai.github.io/authors/alan-murphy/",
        "",
    ]
    for p in posts:
        lines.append("- title: " + repr(p["title"]))
        lines.append('  url: "' + p["url"] + '"')
        lines.append('  date: "' + p["date"] + '"')
        if p.get("excerpt"):
            lines.append('  excerpt: "' + p["excerpt"].replace('"', '\\"') + '"')
        lines.append("")
    OUTPUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    try:
        html = fetch_page(AUTHOR_URL)
        posts = extract_posts(html)
        if not posts:
            print("Warning: No posts found. Keeping existing file.", file=sys.stderr)
            return 0
        write_yaml(posts)
        print(f"Wrote {len(posts)} posts to {OUTPUT_FILE}")
        return 0
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
