#!/usr/bin/env python3
"""
Fetch blog posts by Alan Murphy from Genomics × AI and write _data/genomicsxai_blogs.yml.
Run before Jekyll build to keep the right sidebar up to date.
"""
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import requests
from bs4 import BeautifulSoup

AUTHOR_URL = "https://genomicsxai.github.io/authors/alan-murphy/"
OUTPUT_FILE = Path(__file__).resolve().parent.parent / "_data" / "genomicsxai_blogs.yml"
BASE_URL = "https://genomicsxai.github.io"


def fetch_page(url: str) -> str:
    """Fetch page HTML with a reasonable User-Agent."""
    resp = requests.get(url, timeout=15, headers={"User-Agent": "Jekyll-Blog-Fetcher/1.0"})
    resp.raise_for_status()
    return resp.text


def parse_date(text: str) -> Optional[str]:
    """Parse date string to YYYY-MM-DD. Handles formats like 'Wednesday, February 25, 2026'."""
    if not text or not text.strip():
        return None
    text = text.strip()
    # Try common formats
    for fmt in ("%A, %B %d, %Y", "%B %d, %Y", "%Y-%m-%d", "%d %B %Y"):
        try:
            dt = datetime.strptime(text[:50], fmt)
            return dt.strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def clean_text(text: str) -> str:
    """Collapse a scraped fragment onto one line."""
    return re.sub(r"\s+", " ", (text or "").replace("\xa0", " ")).strip()


def extract_title(anchor) -> str:
    """
    The card's heading only.

    On the author page each card is wrapped *entirely* in its link, so the
    anchor's own text also carries the "Blog Post" label, the date and the read
    time. Read the heading element instead, and only fall back to scrubbing the
    anchor text if the markup ever changes.
    """
    card = anchor.find_parent(class_="article-card") or anchor
    heading = card.select_one(".article-card__title") or card.find(["h1", "h2", "h3", "h4"])
    if heading:
        return clean_text(heading.get_text())

    text = clean_text(anchor.get_text(separator=" "))
    text = re.sub(r"^Blog Post\s*", "", text)
    text = re.sub(r"\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),.*$", "", text)
    text = re.sub(r"\s*·?\s*\d+\s*minutes?\s*read\s*$", "", text, flags=re.I)
    return text.strip(" ·")


def extract_date(anchor, url: str) -> Optional[str]:
    """Publication date, preferring the card's <time datetime="...">."""
    node = anchor.find_parent(class_="article-card") or anchor
    for _ in range(5):
        if not node:
            break
        time_el = node.find("time", datetime=True)
        if time_el and re.match(r"\d{4}-\d{2}-\d{2}", time_el.get("datetime", "")):
            return time_el["datetime"][:10]
        for s in node.find_all(string=True):
            if re.search(r"\d{4}", str(s)) and re.search(
                r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)", str(s), re.I
            ):
                parsed = parse_date(str(s))
                if parsed:
                    return parsed
        node = node.parent
    # Last resort: the year in the slug, e.g. /blogs/2026-003/
    match = re.search(r"/blogs/(\d{4})-\d+/", url)
    return f"{match.group(1)}-01-01" if match else None


def extract_posts(html: str):
    """Extract blog post entries from the author page HTML."""
    soup = BeautifulSoup(html, "html.parser")
    posts = []
    seen_urls = set()

    # Find all links to /blogs/ (post URLs)
    for a in soup.find_all("a", href=True):
        href = a.get("href", "")
        if "/blogs/" not in href:
            continue

        # Normalize URL
        if href.startswith("/"):
            url = BASE_URL + href
        elif href.startswith("http"):
            url = href
        else:
            url = BASE_URL + "/" + href

        if url in seen_urls:
            continue

        title = extract_title(a)
        if not title or len(title) < 5:
            continue

        # Skip nav/header links
        if "Genomics" in title and "AI" in title and len(title) < 25:
            continue

        posts.append({
            "title": title,
            "url": url.rstrip("/") + "/",
            "date": extract_date(a, url) or "2026-01-01",
        })
        seen_urls.add(url)

    # Sort by date descending
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def yaml_quote(value: str) -> str:
    """Double-quoted YAML scalar. (repr() would emit single quotes, in which
    YAML treats a backslash as a literal character rather than an escape.)"""
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_yaml(posts):
    """Write posts to YAML file."""
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/fetch_genomicsxai_blogs.py",
        "# Source: https://genomicsxai.github.io/authors/alan-murphy/",
        "",
    ]
    for p in posts:
        lines.append("- title: " + yaml_quote(p["title"]))
        lines.append("  url: " + yaml_quote(p["url"]))
        lines.append("  date: " + yaml_quote(p["date"]))
        lines.append("")
    OUTPUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    try:
        html = fetch_page(AUTHOR_URL)
        posts = extract_posts(html)
        if not posts:
            print("Warning: No posts found. Keeping existing file.", file=sys.stderr)
            return 0
        write_yaml(posts)
        print(f"Wrote {len(posts)} posts to {OUTPUT_FILE}")
        return 0
    except Exception as e:
        # Keep the existing file and exit 0: a blip fetching the blog should
        # never fail the deploy.
        print(f"Error: {e}. Keeping existing file.", file=sys.stderr)
        return 0


if __name__ == "__main__":
    sys.exit(main())
